testapp:
    build: ./test-app
    links:
      - "fluentd:fluentd"
fluentd:
    build: ./fluentd
    volumes:
        - /var/lib/docker/containers:/var/lib/docker/containers
    links:
      - "elasticsearch:elasticsearch"
elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
kibana:
    image: kibana
    links:
      - "elasticsearch:elasticsearch"
    ports:
      - "5601:5601"
